# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM Project
  pod 'Alamofire-SwiftyJSON'

  target 'MVVM ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
